[package]
name = "spin-mqtt-sdk"
version = { workspace = true }
edition = { workspace = true }
include = ["../spin-mqtt.wit"]

[lib]
name = "spin_mqtt_sdk"

[dependencies]
spin-executor = "3.0.1"
spin-mqtt-macro = { path = "macro" }
wit-bindgen = { workspace = true }